/*******************************************************************************
 * Copyright 2016 Sistcoop, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.jpa.entities;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "DOCUMENT_ATTRIBUTE")
@IdClass(DocumentAttributeEntity.Key.class)
@NamedQueries({
        @NamedQuery(name = "getDocumentAttributesByNameAndValue", query = "select attr from DocumentAttributeEntity attr where attr.name = :name and attr.value = :value"),
        @NamedQuery(name = "deleteDocumentAttributesByAccountingSupplierParty", query = "delete from DocumentAttributeEntity attr where attr.document IN (select doc from DocumentEntity doc where doc.supplierPartyAssignedAccountId=:supplierPartyAssignedAccountId)"),
        @NamedQuery(name = "deleteDocumentAttributesByAccountingCustomerParty", query = "delete from DocumentAttributeEntity attr where attr.document IN (select doc from DocumentEntity doc where doc.customerPartyAssignedAccountId=:customerPartyAssignedAccountId)"),
        @NamedQuery(name = "deleteDocumentAttributesByNameAndDocumentPkId", query = "delete from  DocumentAttributeEntity attr where attr.document.id = :documentPkId and attr.name = :name"),
        @NamedQuery(name = "deleteDocumentAttributesByNameAndDocumentPkIdOtherThan", query = "delete from  DocumentAttributeEntity attr where attr.document.id = :documentPkId and attr.name = :name and attr.id <> :attrId")
})
public class DocumentAttributeEntity {

    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(foreignKey = @ForeignKey, name = "DOCUMENT_ID")
    private DocumentEntity document;

    @Id
    @Column(name = "NAME")
    private String name;

    @Column(name = "VALUE")
    private String value;

    @Column(name = "className")
    private String className;

    public DocumentEntity getDocument() {
        return document;
    }

    public void setDocument(DocumentEntity document) {
        this.document = document;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public static class Key implements Serializable {

        protected DocumentEntity document;

        protected String name;

        public Key() {
        }

        public Key(DocumentEntity document, String name) {
            this.document = document;
            this.name = name;
        }

        public DocumentEntity getDocument() {
            return document;
        }

        public String getName() {
            return name;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            DocumentAttributeEntity.Key key = (DocumentAttributeEntity.Key) o;

            if (name != null ? !name.equals(key.name) : key.name != null) return false;
            if (document != null ? !document.getId().equals(key.document != null ? key.document.getId() : null) : key.document != null)
                return false;

            return true;
        }

        @Override
        public int hashCode() {
            int result = document != null ? document.getId().hashCode() : 0;
            result = 31 * result + (name != null ? name.hashCode() : 0);
            return result;
        }
    }

}
