package org.clarksnut.models;

import org.clarksnut.mapper.document.DocumentMapped.DocumentBean;
import org.clarksnut.models.exceptions.AlreadyImportedDocumentException;

public interface DocumentProvider {

    DocumentModel addDocument(
            String supplierAssignedId,
            String customerAssignedId,
            String documentType,
            ImportedDocumentModel importedDocument,
            DocumentBean bean) throws AlreadyImportedDocumentException;

    /**
     * @param id unique identity generated by the system
     * @return document
     */
    DocumentModel getDocument(String id);

    /**
     * @param type       document type
     * @param assignedId document assigned id
     * @return document
     */
    DocumentModel getDocument(String supplierAssignedId, String type, String assignedId);

    /**
     * @param document document to be removed
     * @return true if document was removed
     */
    boolean removeDocument(DocumentModel document);

}
