package org.clarksnut.models;

import org.clarksnut.models.exceptions.AlreadyImportedDocumentException;
import org.clarksnut.mapper.document.DocumentMapped.DocumentBean;

public interface DocumentProvider {

    DocumentModel addDocument(
            String documentType,
            ImportedDocumentModel importedDocument,
            DocumentBean bean,
            SpaceModel supplier,
            SpaceModel customer) throws AlreadyImportedDocumentException;

    /**
     * @param id unique identity generated by the system
     * @return document
     */
    DocumentModel getDocument(String id);

    /**
     * @param type       document type
     * @param assignedId document assigned id
     * @param supplier   supplier
     * @return document
     */
    DocumentModel getDocument(String type, String assignedId, SpaceModel supplier);

    /**
     * @param document document to be removed
     * @return true if document was removed
     */
    boolean removeDocument(DocumentModel document);

}
