package org.clarksnut.models;

import org.clarksnut.files.FileModel;

public interface ImportedDocumentProvider {

    /**
     * @param file that contains xml file to be persisted
     */
    ImportedDocumentModel importDocument(FileModel file, DocumentProviderType provider);

    /**
     * @param id unique identity generated by the system
     * @return document
     */
    ImportedDocumentModel getImportedDocument(String id);

    /**
     * @param document document to be removed
     * @return true if document was removed
     */
    boolean removeImportedDocument(ImportedDocumentModel document);

}
