package org.clarksnut.documents;

import org.clarksnut.models.SpaceModel;
import org.clarksnut.models.UserModel;

import java.util.Set;

public interface IndexedDocumentProvider {

    /**
     * @param documentId unique identity generated by the system
     * @return document
     */
    IndexedDocumentModel getIndexedDocument(UserModel user, String documentId);

    /**
     * @return list of documents
     */
    SearchResultModel<IndexedDocumentModel> getDocumentsUser(UserModel user, IndexedDocumentQueryModel query, SpaceModel... space);
}
