package org.clarksnut.documents;

import org.clarksnut.files.XmlUBLFileModel;

public interface UnsavedDocumentProvider {

    /**
     * @param file that contains xml file to be persisted
     */
    UnsavedDocumentModel addDocument(XmlUBLFileModel file, UnsavedReasonType reason);

    /**
     * @param id unique identity generated by the system
     * @return document
     */
    UnsavedDocumentModel getDocument(String id);

    /**
     * @param document document to be removed
     * @return true if document was removed
     */
    boolean removeDocument(UnsavedDocumentModel document);

}
