package org.clarksnut.models;

import java.util.List;

public interface SpaceProvider {

    /**
     * @param assignedId unique identity generated by the user
     * @param name       name of the space
     * @param user       owner of space, if the space don't have owner user can be null
     * @return created space
     */
    SpaceModel addSpace(String assignedId, String name, UserModel user);

    /**
     * Find space by id
     *
     * @param id identity auto generated by the system
     * @return space, is not found return null
     */
    SpaceModel getSpace(String id);

    /**
     * @param assignedId unique identity generated by the user
     * @return space, is not found return null
     */
    SpaceModel getByAssignedId(String assignedId);

    /**
     * @param space space to be removed
     * @return true if operation is success
     */
    boolean removeSpace(SpaceModel space);

    /**
     * @param user owner
     * @return spaces owned by user
     */
    List<SpaceModel> getSpaces(UserModel user);

    /**
     * @param user   owner
     * @param offset offset
     * @param limit  limit
     * @return spaces owned by user
     */
    List<SpaceModel> getSpaces(UserModel user, int offset, int limit);

    /**
     * @param query query to apply
     * @return spaces according to query
     */
    List<SpaceModel> getSpaces(QueryModel query);

}
