package org.clarksnut.documents;

import org.clarksnut.models.SpaceModel;
import org.clarksnut.models.UserModel;

import java.util.List;

public interface DocumentUserProvider {

    /**
     * @param documentId unique identity generated by the system
     * @return document
     */
    DocumentUserModel getDocumentUser(UserModel user, String documentId);

    /**
     * @return list of documents
     */
    List<DocumentUserModel> getDocumentsUser(UserModel user, DocumentUserQueryModel query, SpaceModel... space);

    /**
     * @return count results
     */
    int getDocumentsUserSize(UserModel user, DocumentUserQueryModel query);

}
